global.terminal.macro[0]="@chat public="; global.terminal.macro_send[0]=false; 
global.terminal.macro[1]="home";          global.terminal.macro_send[1]=true;
global.terminal.macro[2]="score";         global.terminal.macro_send[2]=true;
global.terminal.macro[3]="rank";          global.terminal.macro_send[3]=true;
global.terminal.macro[4]="trend";         global.terminal.macro_send[4]=true;
global.terminal.macro[5]="build";         global.terminal.macro_send[5]=true;
global.terminal.macro[6]="products";      global.terminal.macro_send[6]=true;
global.terminal.macro[7]="cons";          global.terminal.macro_send[7]=true;
global.terminal.macro[8]="exp";           global.terminal.macro_send[8]=true;
global.terminal.macro[9]="pop";           global.terminal.macro_send[9]=true;
global.terminal.macro[10]="other";        global.terminal.macro_send[10]=true;
global.terminal.macro[11]="@tel #10";     global.terminal.macro_send[11]=true;
global.terminal.macro[12]="+time";        global.terminal.macro_send[12]=true;
global.terminal.macro[13]="+c";           global.terminal.macro_send[13]=true;
global.terminal.macro[14]="+palette";     global.terminal.macro_send[14]=true;
global.terminal.macros=15;
global.terminal.show_macro=0;
